/* tslint:disable */
/* eslint-disable */
/**
 * Spotify apps NestJS backend
 * The API for the Spotify apps
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface ArtistEntity
 */
export interface ArtistEntity {
    /**
     * The ID of the artist
     * @type {string}
     * @memberof ArtistEntity
     */
    'id': string;
    /**
     * The name of the artist
     * @type {string}
     * @memberof ArtistEntity
     */
    'name': string;
}
/**
 * 
 * @export
 * @interface ArtistPlaylistEntity
 */
export interface ArtistPlaylistEntity {
    /**
     * The ID of the \'This is XYZ\' playlist
     * @type {string}
     * @memberof ArtistPlaylistEntity
     */
    'playlist': string;
    /**
     * Contains the ID and name of the artist
     * @type {ArtistEntity}
     * @memberof ArtistPlaylistEntity
     */
    'artist': ArtistEntity;
    /**
     * The number of songs that should be added from the artists \'This is XYZ\' playlist
     * @type {number}
     * @memberof ArtistPlaylistEntity
     */
    'number': number;
}
/**
 * 
 * @export
 * @interface ArtistResponse
 */
export interface ArtistResponse {
    /**
     * Popularity score of the artist
     * @type {number}
     * @memberof ArtistResponse
     */
    'popularity': number;
    /**
     * The ID of the \'This is XYZ\' playlist
     * @type {string}
     * @memberof ArtistResponse
     */
    'playlist': string;
    /**
     * The ID of the artist
     * @type {string}
     * @memberof ArtistResponse
     */
    'id': string;
    /**
     * The name of the artist
     * @type {string}
     * @memberof ArtistResponse
     */
    'name': string;
    /**
     * Array of URLs to artist images
     * @type {Array<string>}
     * @memberof ArtistResponse
     */
    'images': Array<string>;
}
/**
 * 
 * @export
 * @interface ArtistResponseSimple
 */
export interface ArtistResponseSimple {
    /**
     * The ID of the artist
     * @type {string}
     * @memberof ArtistResponseSimple
     */
    'id': string;
    /**
     * The name of the artist
     * @type {string}
     * @memberof ArtistResponseSimple
     */
    'name': string;
    /**
     * Array of URLs to artist images
     * @type {Array<string>}
     * @memberof ArtistResponseSimple
     */
    'images': Array<string>;
}
/**
 * 
 * @export
 * @interface GeneratePlaylistResponseSchema
 */
export interface GeneratePlaylistResponseSchema {
    /**
     * The ID of the generated playlist
     * @type {string}
     * @memberof GeneratePlaylistResponseSchema
     */
    'id': string;
}
/**
 * 
 * @export
 * @interface GeneratePlaylistSchema
 */
export interface GeneratePlaylistSchema {
    /**
     * Contains IDs of \'This is XYZ\' playlists and their artists IDs and names
     * @type {Array<ArtistPlaylistEntity>}
     * @memberof GeneratePlaylistSchema
     */
    'parts': Array<ArtistPlaylistEntity>;
}
/**
 * 
 * @export
 * @interface GetPlaylistResponseSchema
 */
export interface GetPlaylistResponseSchema {
    /**
     * The ID of the playlist
     * @type {string}
     * @memberof GetPlaylistResponseSchema
     */
    'id': string;
    /**
     * Defines if the playlist is set to active or not
     * @type {boolean}
     * @memberof GetPlaylistResponseSchema
     */
    'active': boolean;
    /**
     * 
     * @type {PlaylistsResponse}
     * @memberof GetPlaylistResponseSchema
     */
    'playlist': PlaylistsResponse;
    /**
     * 
     * @type {Array<ArtistResponseSimple>}
     * @memberof GetPlaylistResponseSchema
     */
    'artists': Array<ArtistResponseSimple>;
}
/**
 * 
 * @export
 * @interface PlaylistsResponse
 */
export interface PlaylistsResponse {
    /**
     * The name of the playlist
     * @type {string}
     * @memberof PlaylistsResponse
     */
    'name': string;
    /**
     * The description of the playlist
     * @type {string}
     * @memberof PlaylistsResponse
     */
    'description': string;
    /**
     * Array of URLs to playlist images
     * @type {Array<string>}
     * @memberof PlaylistsResponse
     */
    'images': Array<string>;
}
/**
 * 
 * @export
 * @interface SearchArtistAlternativeResponseSchema
 */
export interface SearchArtistAlternativeResponseSchema {
    /**
     * The search query
     * @type {string}
     * @memberof SearchArtistAlternativeResponseSchema
     */
    'query': string;
    /**
     * Offset to the next artist batch
     * @type {number}
     * @memberof SearchArtistAlternativeResponseSchema
     */
    'next': number | null;
    /**
     * The artist that is returned
     * @type {Array<ArtistResponse>}
     * @memberof SearchArtistAlternativeResponseSchema
     */
    'artists': Array<ArtistResponse>;
}
/**
 * 
 * @export
 * @interface SearchArtistResponseSchema
 */
export interface SearchArtistResponseSchema {
    /**
     * The search query
     * @type {string}
     * @memberof SearchArtistResponseSchema
     */
    'query': string;
    /**
     * Offset to the next artist batch
     * @type {number}
     * @memberof SearchArtistResponseSchema
     */
    'next': number | null;
    /**
     * The artist that is returned
     * @type {ArtistResponse}
     * @memberof SearchArtistResponseSchema
     */
    'artist': ArtistResponse | null;
}

/**
 * MergerApi - axios parameter creator
 * @export
 */
export const MergerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {GeneratePlaylistSchema} generatePlaylistSchema 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mergerControllerGeneratePlaylist: async (generatePlaylistSchema: GeneratePlaylistSchema, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'generatePlaylistSchema' is not null or undefined
            assertParamExists('mergerControllerGeneratePlaylist', 'generatePlaylistSchema', generatePlaylistSchema)
            const localVarPath = `/merger/playlists`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(generatePlaylistSchema, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} playlist 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mergerControllerGetPlaylist: async (playlist: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'playlist' is not null or undefined
            assertParamExists('mergerControllerGetPlaylist', 'playlist', playlist)
            const localVarPath = `/merger/playlists/{playlist}`
                .replace(`{${"playlist"}}`, encodeURIComponent(String(playlist)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mergerControllerGetPlaylists: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/merger/playlists`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} playlist 
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mergerControllerRefreshPlaylist: async (playlist: string, body: object, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'playlist' is not null or undefined
            assertParamExists('mergerControllerRefreshPlaylist', 'playlist', playlist)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('mergerControllerRefreshPlaylist', 'body', body)
            const localVarPath = `/merger/playlists/{playlist}/refresh`
                .replace(`{${"playlist"}}`, encodeURIComponent(String(playlist)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} name The name of the artist to search
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mergerControllerSearchArtist: async (name: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            assertParamExists('mergerControllerSearchArtist', 'name', name)
            const localVarPath = `/merger/artist`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} name The name of the artist to search
         * @param {number} offset The offset for viable artists
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mergerControllerSearchArtistAlternatives: async (name: string, offset: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            assertParamExists('mergerControllerSearchArtistAlternatives', 'name', name)
            // verify required parameter 'offset' is not null or undefined
            assertParamExists('mergerControllerSearchArtistAlternatives', 'offset', offset)
            const localVarPath = `/merger/artist/alternatives`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} playlist 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mergerControllerSetPlaylistActive: async (playlist: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'playlist' is not null or undefined
            assertParamExists('mergerControllerSetPlaylistActive', 'playlist', playlist)
            const localVarPath = `/merger/playlists/{playlist}/active`
                .replace(`{${"playlist"}}`, encodeURIComponent(String(playlist)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} playlist 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mergerControllerSetPlaylistInactive: async (playlist: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'playlist' is not null or undefined
            assertParamExists('mergerControllerSetPlaylistInactive', 'playlist', playlist)
            const localVarPath = `/merger/playlists/{playlist}/inactive`
                .replace(`{${"playlist"}}`, encodeURIComponent(String(playlist)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MergerApi - functional programming interface
 * @export
 */
export const MergerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MergerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {GeneratePlaylistSchema} generatePlaylistSchema 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mergerControllerGeneratePlaylist(generatePlaylistSchema: GeneratePlaylistSchema, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GeneratePlaylistResponseSchema>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.mergerControllerGeneratePlaylist(generatePlaylistSchema, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} playlist 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mergerControllerGetPlaylist(playlist: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetPlaylistResponseSchema>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.mergerControllerGetPlaylist(playlist, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mergerControllerGetPlaylists(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GetPlaylistResponseSchema>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.mergerControllerGetPlaylists(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} playlist 
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mergerControllerRefreshPlaylist(playlist: string, body: object, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.mergerControllerRefreshPlaylist(playlist, body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} name The name of the artist to search
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mergerControllerSearchArtist(name: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SearchArtistResponseSchema>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.mergerControllerSearchArtist(name, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} name The name of the artist to search
         * @param {number} offset The offset for viable artists
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mergerControllerSearchArtistAlternatives(name: string, offset: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SearchArtistAlternativeResponseSchema>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.mergerControllerSearchArtistAlternatives(name, offset, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} playlist 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mergerControllerSetPlaylistActive(playlist: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.mergerControllerSetPlaylistActive(playlist, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} playlist 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mergerControllerSetPlaylistInactive(playlist: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.mergerControllerSetPlaylistInactive(playlist, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * MergerApi - factory interface
 * @export
 */
export const MergerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MergerApiFp(configuration)
    return {
        /**
         * 
         * @param {GeneratePlaylistSchema} generatePlaylistSchema 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mergerControllerGeneratePlaylist(generatePlaylistSchema: GeneratePlaylistSchema, options?: any): AxiosPromise<GeneratePlaylistResponseSchema> {
            return localVarFp.mergerControllerGeneratePlaylist(generatePlaylistSchema, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} playlist 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mergerControllerGetPlaylist(playlist: string, options?: any): AxiosPromise<GetPlaylistResponseSchema> {
            return localVarFp.mergerControllerGetPlaylist(playlist, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mergerControllerGetPlaylists(options?: any): AxiosPromise<Array<GetPlaylistResponseSchema>> {
            return localVarFp.mergerControllerGetPlaylists(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} playlist 
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mergerControllerRefreshPlaylist(playlist: string, body: object, options?: any): AxiosPromise<void> {
            return localVarFp.mergerControllerRefreshPlaylist(playlist, body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} name The name of the artist to search
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mergerControllerSearchArtist(name: string, options?: any): AxiosPromise<SearchArtistResponseSchema> {
            return localVarFp.mergerControllerSearchArtist(name, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} name The name of the artist to search
         * @param {number} offset The offset for viable artists
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mergerControllerSearchArtistAlternatives(name: string, offset: number, options?: any): AxiosPromise<SearchArtistAlternativeResponseSchema> {
            return localVarFp.mergerControllerSearchArtistAlternatives(name, offset, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} playlist 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mergerControllerSetPlaylistActive(playlist: string, options?: any): AxiosPromise<void> {
            return localVarFp.mergerControllerSetPlaylistActive(playlist, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} playlist 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mergerControllerSetPlaylistInactive(playlist: string, options?: any): AxiosPromise<void> {
            return localVarFp.mergerControllerSetPlaylistInactive(playlist, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MergerApi - object-oriented interface
 * @export
 * @class MergerApi
 * @extends {BaseAPI}
 */
export class MergerApi extends BaseAPI {
    /**
     * 
     * @param {GeneratePlaylistSchema} generatePlaylistSchema 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MergerApi
     */
    public mergerControllerGeneratePlaylist(generatePlaylistSchema: GeneratePlaylistSchema, options?: AxiosRequestConfig) {
        return MergerApiFp(this.configuration).mergerControllerGeneratePlaylist(generatePlaylistSchema, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} playlist 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MergerApi
     */
    public mergerControllerGetPlaylist(playlist: string, options?: AxiosRequestConfig) {
        return MergerApiFp(this.configuration).mergerControllerGetPlaylist(playlist, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MergerApi
     */
    public mergerControllerGetPlaylists(options?: AxiosRequestConfig) {
        return MergerApiFp(this.configuration).mergerControllerGetPlaylists(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} playlist 
     * @param {object} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MergerApi
     */
    public mergerControllerRefreshPlaylist(playlist: string, body: object, options?: AxiosRequestConfig) {
        return MergerApiFp(this.configuration).mergerControllerRefreshPlaylist(playlist, body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} name The name of the artist to search
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MergerApi
     */
    public mergerControllerSearchArtist(name: string, options?: AxiosRequestConfig) {
        return MergerApiFp(this.configuration).mergerControllerSearchArtist(name, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} name The name of the artist to search
     * @param {number} offset The offset for viable artists
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MergerApi
     */
    public mergerControllerSearchArtistAlternatives(name: string, offset: number, options?: AxiosRequestConfig) {
        return MergerApiFp(this.configuration).mergerControllerSearchArtistAlternatives(name, offset, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} playlist 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MergerApi
     */
    public mergerControllerSetPlaylistActive(playlist: string, options?: AxiosRequestConfig) {
        return MergerApiFp(this.configuration).mergerControllerSetPlaylistActive(playlist, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} playlist 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MergerApi
     */
    public mergerControllerSetPlaylistInactive(playlist: string, options?: AxiosRequestConfig) {
        return MergerApiFp(this.configuration).mergerControllerSetPlaylistInactive(playlist, options).then((request) => request(this.axios, this.basePath));
    }
}


