# Frontend Mashup Deploy to Cloud Builder / App Engine

steps:
  - name: gcr.io/cloud-builders/npm
    args:
      - install
    dir: frontends/mashup

  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - |
        cp ./env.dev.example.ts ./env.dev.ts
        touch ./env.prod.ts
        echo "$_MASHUP_ENV_FILE_TEXT" >> ./env.prod.ts
        cat ./env.prod.ts
    dir: frontends/mashup
    entrypoint: bash

  - name: 'node:16.10'
    args:
      - run
      - build
      - '--prod'
    dir: frontends/mashup
    entrypoint: npm

  - name: gcr.io/cloud-builders/gcloud
    args:
      - app
      - deploy
      - '--version=prod'
    dir: frontends/mashup

options:
  logging: CLOUD_LOGGING_ONLY
