runtime: python27
api_version: 1
threadsafe: yes

handlers:
  - url: /(.*\.(gif|png|jpg|css|js)(|\.map))$
    static_files: dist/mashup/\1
    upload: dist/mashup/(.*)(|\.map)
    secure: always

  - url: /(.*)
    static_files: dist/mashup/index.html
    upload: dist/mashup/index.html
    secure: always

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE
