/* tslint:disable */
/* eslint-disable */
/**
 * Spotify apps NestJS backend
 * The API for the Spotify apps
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface ArtistFull
 */
export interface ArtistFull {
    /**
     * Number of songs to select from the artist
     * @type {number}
     * @memberof ArtistFull
     */
    'number': number;
    /**
     * The ID of the \'This is XYZ\' playlist
     * @type {string}
     * @memberof ArtistFull
     */
    'playlist': string;
    /**
     * The ID of the artist
     * @type {string}
     * @memberof ArtistFull
     */
    'id': string;
    /**
     * The name of the artist
     * @type {string}
     * @memberof ArtistFull
     */
    'name': string;
}
/**
 * 
 * @export
 * @interface ArtistResponseFull
 */
export interface ArtistResponseFull {
    /**
     * Array of URLs to artist images
     * @type {Array<string>}
     * @memberof ArtistResponseFull
     */
    'images': Array<string>;
    /**
     * Number of songs to select from the artist
     * @type {number}
     * @memberof ArtistResponseFull
     */
    'number': number;
    /**
     * The ID of the \'This is XYZ\' playlist
     * @type {string}
     * @memberof ArtistResponseFull
     */
    'playlist': string;
    /**
     * The ID of the artist
     * @type {string}
     * @memberof ArtistResponseFull
     */
    'id': string;
    /**
     * The name of the artist
     * @type {string}
     * @memberof ArtistResponseFull
     */
    'name': string;
}
/**
 * 
 * @export
 * @interface GeneratePlaylistResponseSchema
 */
export interface GeneratePlaylistResponseSchema {
    /**
     * The ID of the generated playlist
     * @type {string}
     * @memberof GeneratePlaylistResponseSchema
     */
    'id': string;
}
/**
 * 
 * @export
 * @interface GetPlaylistResponseSchema
 */
export interface GetPlaylistResponseSchema {
    /**
     * The ID of the playlist
     * @type {string}
     * @memberof GetPlaylistResponseSchema
     */
    'id': string;
    /**
     * 
     * @type {PlaylistsResponse}
     * @memberof GetPlaylistResponseSchema
     */
    'playlist': PlaylistsResponse;
    /**
     * 
     * @type {Array<ArtistResponseFull>}
     * @memberof GetPlaylistResponseSchema
     */
    'artists': Array<ArtistResponseFull>;
    /**
     * 
     * @type {MetadataResponse}
     * @memberof GetPlaylistResponseSchema
     */
    'metadata': MetadataResponse;
}
/**
 * 
 * @export
 * @interface MetadataResponse
 */
export interface MetadataResponse {
    /**
     * Timestamp of last update
     * @type {number}
     * @memberof MetadataResponse
     */
    'updated': number;
    /**
     * Timestamp of creation
     * @type {number}
     * @memberof MetadataResponse
     */
    'created': number;
    /**
     * Defines if playlist refreshing is set to active or not
     * @type {boolean}
     * @memberof MetadataResponse
     */
    'active': boolean;
    /**
     * Refresh playlist every X days
     * @type {number}
     * @memberof MetadataResponse
     */
    'frequency': number;
}
/**
 * 
 * @export
 * @interface PlaylistsResponse
 */
export interface PlaylistsResponse {
    /**
     * The name of the playlist
     * @type {string}
     * @memberof PlaylistsResponse
     */
    'name': string;
    /**
     * The description of the playlist
     * @type {string}
     * @memberof PlaylistsResponse
     */
    'description': string;
    /**
     * Array of URLs to playlist images
     * @type {Array<string>}
     * @memberof PlaylistsResponse
     */
    'images': Array<string>;
}
/**
 * 
 * @export
 * @interface SearchArtistResponseSchema
 */
export interface SearchArtistResponseSchema {
    /**
     * The search query
     * @type {string}
     * @memberof SearchArtistResponseSchema
     */
    'query': string;
    /**
     * Offset to the next artist batch
     * @type {number}
     * @memberof SearchArtistResponseSchema
     */
    'next': number | null;
    /**
     * 
     * @type {SearchArtistResponseSchemaArtist}
     * @memberof SearchArtistResponseSchema
     */
    'artist': SearchArtistResponseSchemaArtist | null;
}
/**
 * The artist that is returned
 * @export
 * @interface SearchArtistResponseSchemaArtist
 */
export interface SearchArtistResponseSchemaArtist {
    /**
     * Array of URLs to artist images
     * @type {Array<string>}
     * @memberof SearchArtistResponseSchemaArtist
     */
    'images': Array<string>;
    /**
     * Number of songs to select from the artist
     * @type {number}
     * @memberof SearchArtistResponseSchemaArtist
     */
    'number': number;
    /**
     * The ID of the \'This is XYZ\' playlist
     * @type {string}
     * @memberof SearchArtistResponseSchemaArtist
     */
    'playlist': string;
    /**
     * The ID of the artist
     * @type {string}
     * @memberof SearchArtistResponseSchemaArtist
     */
    'id': string;
    /**
     * The name of the artist
     * @type {string}
     * @memberof SearchArtistResponseSchemaArtist
     */
    'name': string;
}
/**
 * 
 * @export
 * @interface SubmitPlaylistSchema
 */
export interface SubmitPlaylistSchema {
    /**
     * Contains IDs of \'This is XYZ\' playlists and their artists IDs and names
     * @type {Array<ArtistFull>}
     * @memberof SubmitPlaylistSchema
     */
    'parts': Array<ArtistFull>;
    /**
     * Defines if playlist refreshing is set to active or not
     * @type {boolean}
     * @memberof SubmitPlaylistSchema
     */
    'active': boolean;
    /**
     * Refresh playlist every X days
     * @type {number}
     * @memberof SubmitPlaylistSchema
     */
    'frequency': number;
    /**
     * Defines if the title of the playlist should be updated
     * @type {boolean}
     * @memberof SubmitPlaylistSchema
     */
    'updateTitle': boolean;
    /**
     * Defines if the description of the playlist should be updated
     * @type {boolean}
     * @memberof SubmitPlaylistSchema
     */
    'updateDescription': boolean;
}

/**
 * MashupApi - axios parameter creator
 * @export
 */
export const MashupApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mashupControllerCheckAuth: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/mashup/auth`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {SubmitPlaylistSchema} submitPlaylistSchema 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mashupControllerGeneratePlaylist: async (submitPlaylistSchema: SubmitPlaylistSchema, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'submitPlaylistSchema' is not null or undefined
            assertParamExists('mashupControllerGeneratePlaylist', 'submitPlaylistSchema', submitPlaylistSchema)
            const localVarPath = `/mashup/playlists`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(submitPlaylistSchema, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} playlist 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mashupControllerGetPlaylist: async (playlist: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'playlist' is not null or undefined
            assertParamExists('mashupControllerGetPlaylist', 'playlist', playlist)
            const localVarPath = `/mashup/playlists/{playlist}`
                .replace(`{${"playlist"}}`, encodeURIComponent(String(playlist)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mashupControllerGetPlaylists: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/mashup/playlists`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} playlist 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mashupControllerRefreshPlaylist: async (playlist: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'playlist' is not null or undefined
            assertParamExists('mashupControllerRefreshPlaylist', 'playlist', playlist)
            const localVarPath = `/mashup/playlists/{playlist}/refresh`
                .replace(`{${"playlist"}}`, encodeURIComponent(String(playlist)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} name The name of the artist to search
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mashupControllerSearchArtist: async (name: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            assertParamExists('mashupControllerSearchArtist', 'name', name)
            const localVarPath = `/mashup/artist`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} playlist 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mashupControllerSetPlaylistActive: async (playlist: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'playlist' is not null or undefined
            assertParamExists('mashupControllerSetPlaylistActive', 'playlist', playlist)
            const localVarPath = `/mashup/playlists/{playlist}/active`
                .replace(`{${"playlist"}}`, encodeURIComponent(String(playlist)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} playlist 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mashupControllerSetPlaylistInactive: async (playlist: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'playlist' is not null or undefined
            assertParamExists('mashupControllerSetPlaylistInactive', 'playlist', playlist)
            const localVarPath = `/mashup/playlists/{playlist}/inactive`
                .replace(`{${"playlist"}}`, encodeURIComponent(String(playlist)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} playlist 
         * @param {SubmitPlaylistSchema} submitPlaylistSchema 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mashupControllerUpdatePlaylist: async (playlist: string, submitPlaylistSchema: SubmitPlaylistSchema, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'playlist' is not null or undefined
            assertParamExists('mashupControllerUpdatePlaylist', 'playlist', playlist)
            // verify required parameter 'submitPlaylistSchema' is not null or undefined
            assertParamExists('mashupControllerUpdatePlaylist', 'submitPlaylistSchema', submitPlaylistSchema)
            const localVarPath = `/mashup/playlists/{playlist}`
                .replace(`{${"playlist"}}`, encodeURIComponent(String(playlist)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(submitPlaylistSchema, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MashupApi - functional programming interface
 * @export
 */
export const MashupApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MashupApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mashupControllerCheckAuth(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.mashupControllerCheckAuth(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {SubmitPlaylistSchema} submitPlaylistSchema 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mashupControllerGeneratePlaylist(submitPlaylistSchema: SubmitPlaylistSchema, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GeneratePlaylistResponseSchema>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.mashupControllerGeneratePlaylist(submitPlaylistSchema, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} playlist 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mashupControllerGetPlaylist(playlist: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetPlaylistResponseSchema>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.mashupControllerGetPlaylist(playlist, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mashupControllerGetPlaylists(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GetPlaylistResponseSchema>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.mashupControllerGetPlaylists(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} playlist 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mashupControllerRefreshPlaylist(playlist: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.mashupControllerRefreshPlaylist(playlist, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} name The name of the artist to search
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mashupControllerSearchArtist(name: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SearchArtistResponseSchema>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.mashupControllerSearchArtist(name, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} playlist 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mashupControllerSetPlaylistActive(playlist: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.mashupControllerSetPlaylistActive(playlist, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} playlist 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mashupControllerSetPlaylistInactive(playlist: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.mashupControllerSetPlaylistInactive(playlist, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} playlist 
         * @param {SubmitPlaylistSchema} submitPlaylistSchema 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mashupControllerUpdatePlaylist(playlist: string, submitPlaylistSchema: SubmitPlaylistSchema, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GeneratePlaylistResponseSchema>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.mashupControllerUpdatePlaylist(playlist, submitPlaylistSchema, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * MashupApi - factory interface
 * @export
 */
export const MashupApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MashupApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mashupControllerCheckAuth(options?: any): AxiosPromise<void> {
            return localVarFp.mashupControllerCheckAuth(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SubmitPlaylistSchema} submitPlaylistSchema 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mashupControllerGeneratePlaylist(submitPlaylistSchema: SubmitPlaylistSchema, options?: any): AxiosPromise<GeneratePlaylistResponseSchema> {
            return localVarFp.mashupControllerGeneratePlaylist(submitPlaylistSchema, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} playlist 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mashupControllerGetPlaylist(playlist: string, options?: any): AxiosPromise<GetPlaylistResponseSchema> {
            return localVarFp.mashupControllerGetPlaylist(playlist, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mashupControllerGetPlaylists(options?: any): AxiosPromise<Array<GetPlaylistResponseSchema>> {
            return localVarFp.mashupControllerGetPlaylists(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} playlist 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mashupControllerRefreshPlaylist(playlist: string, options?: any): AxiosPromise<void> {
            return localVarFp.mashupControllerRefreshPlaylist(playlist, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} name The name of the artist to search
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mashupControllerSearchArtist(name: string, options?: any): AxiosPromise<SearchArtistResponseSchema> {
            return localVarFp.mashupControllerSearchArtist(name, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} playlist 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mashupControllerSetPlaylistActive(playlist: string, options?: any): AxiosPromise<void> {
            return localVarFp.mashupControllerSetPlaylistActive(playlist, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} playlist 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mashupControllerSetPlaylistInactive(playlist: string, options?: any): AxiosPromise<void> {
            return localVarFp.mashupControllerSetPlaylistInactive(playlist, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} playlist 
         * @param {SubmitPlaylistSchema} submitPlaylistSchema 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mashupControllerUpdatePlaylist(playlist: string, submitPlaylistSchema: SubmitPlaylistSchema, options?: any): AxiosPromise<GeneratePlaylistResponseSchema> {
            return localVarFp.mashupControllerUpdatePlaylist(playlist, submitPlaylistSchema, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MashupApi - object-oriented interface
 * @export
 * @class MashupApi
 * @extends {BaseAPI}
 */
export class MashupApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MashupApi
     */
    public mashupControllerCheckAuth(options?: AxiosRequestConfig) {
        return MashupApiFp(this.configuration).mashupControllerCheckAuth(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SubmitPlaylistSchema} submitPlaylistSchema 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MashupApi
     */
    public mashupControllerGeneratePlaylist(submitPlaylistSchema: SubmitPlaylistSchema, options?: AxiosRequestConfig) {
        return MashupApiFp(this.configuration).mashupControllerGeneratePlaylist(submitPlaylistSchema, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} playlist 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MashupApi
     */
    public mashupControllerGetPlaylist(playlist: string, options?: AxiosRequestConfig) {
        return MashupApiFp(this.configuration).mashupControllerGetPlaylist(playlist, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MashupApi
     */
    public mashupControllerGetPlaylists(options?: AxiosRequestConfig) {
        return MashupApiFp(this.configuration).mashupControllerGetPlaylists(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} playlist 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MashupApi
     */
    public mashupControllerRefreshPlaylist(playlist: string, options?: AxiosRequestConfig) {
        return MashupApiFp(this.configuration).mashupControllerRefreshPlaylist(playlist, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} name The name of the artist to search
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MashupApi
     */
    public mashupControllerSearchArtist(name: string, options?: AxiosRequestConfig) {
        return MashupApiFp(this.configuration).mashupControllerSearchArtist(name, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} playlist 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MashupApi
     */
    public mashupControllerSetPlaylistActive(playlist: string, options?: AxiosRequestConfig) {
        return MashupApiFp(this.configuration).mashupControllerSetPlaylistActive(playlist, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} playlist 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MashupApi
     */
    public mashupControllerSetPlaylistInactive(playlist: string, options?: AxiosRequestConfig) {
        return MashupApiFp(this.configuration).mashupControllerSetPlaylistInactive(playlist, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} playlist 
     * @param {SubmitPlaylistSchema} submitPlaylistSchema 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MashupApi
     */
    public mashupControllerUpdatePlaylist(playlist: string, submitPlaylistSchema: SubmitPlaylistSchema, options?: AxiosRequestConfig) {
        return MashupApiFp(this.configuration).mashupControllerUpdatePlaylist(playlist, submitPlaylistSchema, options).then((request) => request(this.axios, this.basePath));
    }
}


